---
server:
  port: 8080
database:
  host: localhost
  password: root
  port: 3306
  username: root
features:
  allow_register: false
  password_hash_cost: 16
path:
  cache: "/var/osc/cache"
  storage: "/var/osc/storage"